services:
  space-weather:
    build: .
    container_name: space-weather
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - NASA_API_KEY=${NASA_API_KEY}
    restart: unless-stopped
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    container_name: space-weather-redis
    ports:
       - "6379:6379"
    restart: unless-stopped
